### ISSUE TITLE
Home Page a bit broken with new update (94.0)

### ISSUE THREAD

**Issue by 1-minute-to-midnight** [tomatopickle/Glox#1]
The search bar is dark and not rounded anymore and the top sites background is also dark:
![image](https://user-images.githubusercontent.com/70870070/140310164-a14b27b0-84b6-4c10-9f66-b1ea2dccc077.png)

**Comment by abaanshanid** [comment]
Yeah, I've notoced this. I'll fix it by tommorrow

**Comment by tomatopickle** [comment]
Eat

**Comment by abaanshanid** [comment]
Fixed, please download [gloxksin.zip](https://github.com/tomatopickle/Glox/blob/main/gloxskin.zip) and update the theme
